name: qanoun_sahl
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: null
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_cached_pdfview: ^0.4.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri.ttf
